module.exports = { '1': { name: 'Annie', title: 'the Dark Child' },
  '2': { name: 'Olaf', title: 'the Berserker' },
  '3': { name: 'Galio', title: 'the Colossus' },
  '4': { name: 'Twisted Fate', title: 'the Card Master' },
  '5': { name: 'Xin Zhao', title: 'the Seneschal of Demacia' },
  '6': { name: 'Urgot', title: 'the Dreadnought' },
  '7': { name: 'LeBlanc', title: 'the Deceiver' },
  '8': { name: 'Vladimir', title: 'the Crimson Reaper' },
  '9': { name: 'Fiddlesticks', title: 'the Harbinger of Doom' },
  '10': { name: 'Kayle', title: 'The Judicator' },
  '11': { name: 'Master Yi', title: 'the Wuju Bladesman' },
  '12': { name: 'Alistar', title: 'the Minotaur' },
  '13': { name: 'Ryze', title: 'the Rune Mage' },
  '14': { name: 'Sion', title: 'The Undead Juggernaut' },
  '15': { name: 'Sivir', title: 'the Battle Mistress' },
  '16': { name: 'Soraka', title: 'the Starchild' },
  '17': { name: 'Teemo', title: 'the Swift Scout' },
  '18': { name: 'Tristana', title: 'the Yordle Gunner' },
  '19': { name: 'Warwick', title: 'the Uncaged Wrath of Zaun' },
  '20': { name: 'Nunu & Willump', title: 'the Boy and His Yeti' },
  '21': { name: 'Miss Fortune', title: 'the Bounty Hunter' },
  '22': { name: 'Ashe', title: 'the Frost Archer' },
  '23': { name: 'Tryndamere', title: 'the Barbarian King' },
  '24': { name: 'Jax', title: 'Grandmaster at Arms' },
  '25': { name: 'Morgana', title: 'Fallen Angel' },
  '26': { name: 'Zilean', title: 'the Chronokeeper' },
  '27': { name: 'Singed', title: 'the Mad Chemist' },
  '28': { name: 'Evelynn', title: 'Agony\'s Embrace' },
  '29': { name: 'Twitch', title: 'the Plague Rat' },
  '30': { name: 'Karthus', title: 'the Deathsinger' },
  '31': { name: 'Cho\'Gath', title: 'the Terror of the Void' },
  '32': { name: 'Amumu', title: 'the Sad Mummy' },
  '33': { name: 'Rammus', title: 'the Armordillo' },
  '34': { name: 'Anivia', title: 'the Cryophoenix' },
  '35': { name: 'Shaco', title: 'the Demon Jester' },
  '36': { name: 'Dr. Mundo', title: 'the Madman of Zaun' },
  '37': { name: 'Sona', title: 'Maven of the Strings' },
  '38': { name: 'Kassadin', title: 'the Void Walker' },
  '39': { name: 'Irelia', title: 'the Blade Dancer' },
  '40': { name: 'Janna', title: 'the Storm\'s Fury' },
  '41': { name: 'Gangplank', title: 'the Saltwater Scourge' },
  '42': { name: 'Corki', title: 'the Daring Bombardier' },
  '43': { name: 'Karma', title: 'the Enlightened One' },
  '44': { name: 'Taric', title: 'the Shield of Valoran' },
  '45': { name: 'Veigar', title: 'the Tiny Master of Evil' },
  '48': { name: 'Trundle', title: 'the Troll King' },
  '50': { name: 'Swain', title: 'the Noxian Grand General' },
  '51': { name: 'Caitlyn', title: 'the Sheriff of Piltover' },
  '53': { name: 'Blitzcrank', title: 'the Great Steam Golem' },
  '54': { name: 'Malphite', title: 'Shard of the Monolith' },
  '55': { name: 'Katarina', title: 'the Sinister Blade' },
  '56': { name: 'Nocturne', title: 'the Eternal Nightmare' },
  '57': { name: 'Maokai', title: 'the Twisted Treant' },
  '58': { name: 'Renekton', title: 'the Butcher of the Sands' },
  '59': { name: 'Jarvan IV', title: 'the Exemplar of Demacia' },
  '60': { name: 'Elise', title: 'the Spider Queen' },
  '61': { name: 'Orianna', title: 'the Lady of Clockwork' },
  '62': { name: 'Wukong', title: 'the Monkey King' },
  '63': { name: 'Brand', title: 'the Burning Vengeance' },
  '64': { name: 'Lee Sin', title: 'the Blind Monk' },
  '67': { name: 'Vayne', title: 'the Night Hunter' },
  '68': { name: 'Rumble', title: 'the Mechanized Menace' },
  '69': { name: 'Cassiopeia', title: 'the Serpent\'s Embrace' },
  '72': { name: 'Skarner', title: 'the Crystal Vanguard' },
  '74': { name: 'Heimerdinger', title: 'the Revered Inventor' },
  '75': { name: 'Nasus', title: 'the Curator of the Sands' },
  '76': { name: 'Nidalee', title: 'the Bestial Huntress' },
  '77': { name: 'Udyr', title: 'the Spirit Walker' },
  '78': { name: 'Poppy', title: 'Keeper of the Hammer' },
  '79': { name: 'Gragas', title: 'the Rabble Rouser' },
  '80': { name: 'Pantheon', title: 'the Artisan of War' },
  '81': { name: 'Ezreal', title: 'the Prodigal Explorer' },
  '82': { name: 'Mordekaiser', title: 'the Iron Revenant' },
  '83': { name: 'Yorick', title: 'Shepherd of Souls' },
  '84': { name: 'Akali', title: 'the Rogue Assassin' },
  '85': { name: 'Kennen', title: 'the Heart of the Tempest' },
  '86': { name: 'Garen', title: 'The Might of Demacia' },
  '89': { name: 'Leona', title: 'the Radiant Dawn' },
  '90': { name: 'Malzahar', title: 'the Prophet of the Void' },
  '91': { name: 'Talon', title: 'the Blade\'s Shadow' },
  '92': { name: 'Riven', title: 'the Exile' },
  '96': { name: 'Kog\'Maw', title: 'the Mouth of the Abyss' },
  '98': { name: 'Shen', title: 'the Eye of Twilight' },
  '99': { name: 'Lux', title: 'the Lady of Luminosity' },
  '101': { name: 'Xerath', title: 'the Magus Ascendant' },
  '102': { name: 'Shyvana', title: 'the Half-Dragon' },
  '103': { name: 'Ahri', title: 'the Nine-Tailed Fox' },
  '104': { name: 'Graves', title: 'the Outlaw' },
  '105': { name: 'Fizz', title: 'the Tidal Trickster' },
  '106': { name: 'Volibear', title: 'the Thunder\'s Roar' },
  '107': { name: 'Rengar', title: 'the Pridestalker' },
  '110': { name: 'Varus', title: 'the Arrow of Retribution' },
  '111': { name: 'Nautilus', title: 'the Titan of the Depths' },
  '112': { name: 'Viktor', title: 'the Machine Herald' },
  '113': { name: 'Sejuani', title: 'Fury of the North' },
  '114': { name: 'Fiora', title: 'the Grand Duelist' },
  '115': { name: 'Ziggs', title: 'the Hexplosives Expert' },
  '117': { name: 'Lulu', title: 'the Fae Sorceress' },
  '119': { name: 'Draven', title: 'the Glorious Executioner' },
  '120': { name: 'Hecarim', title: 'the Shadow of War' },
  '121': { name: 'Kha\'Zix', title: 'the Voidreaver' },
  '122': { name: 'Darius', title: 'the Hand of Noxus' },
  '126': { name: 'Jayce', title: 'the Defender of Tomorrow' },
  '127': { name: 'Lissandra', title: 'the Ice Witch' },
  '131': { name: 'Diana', title: 'Scorn of the Moon' },
  '133': { name: 'Quinn', title: 'Demacia\'s Wings' },
  '134': { name: 'Syndra', title: 'the Dark Sovereign' },
  '136': { name: 'Aurelion Sol', title: 'The Star Forger' },
  '141': { name: 'Kayn', title: 'the Shadow Reaper' },
  '142': { name: 'Zoe', title: 'the Aspect of Twilight' },
  '143': { name: 'Zyra', title: 'Rise of the Thorns' },
  '145': { name: 'Kai\'Sa', title: 'Daughter of the Void' },
  '150': { name: 'Gnar', title: 'the Missing Link' },
  '154': { name: 'Zac', title: 'the Secret Weapon' },
  '157': { name: 'Yasuo', title: 'the Unforgiven' },
  '161': { name: 'Vel\'Koz', title: 'the Eye of the Void' },
  '163': { name: 'Taliyah', title: 'the Stoneweaver' },
  '164': { name: 'Camille', title: 'the Steel Shadow' },
  '201': { name: 'Braum', title: 'the Heart of the Freljord' },
  '202': { name: 'Jhin', title: 'the Virtuoso' },
  '203': { name: 'Kindred', title: 'The Eternal Hunters' },
  '222': { name: 'Jinx', title: 'the Loose Cannon' },
  '223': { name: 'Tahm Kench', title: 'the River King' },
  '236': { name: 'Lucian', title: 'the Purifier' },
  '238': { name: 'Zed', title: 'the Master of Shadows' },
  '240': { name: 'Kled', title: 'the Cantankerous Cavalier' },
  '245': { name: 'Ekko', title: 'the Boy Who Shattered Time' },
  '254': { name: 'Vi', title: 'the Piltover Enforcer' },
  '266': { name: 'Aatrox', title: 'the Darkin Blade' },
  '267': { name: 'Nami', title: 'the Tidecaller' },
  '268': { name: 'Azir', title: 'the Emperor of the Sands' },
  '412': { name: 'Thresh', title: 'the Chain Warden' },
  '420': { name: 'Illaoi', title: 'the Kraken Priestess' },
  '421': { name: 'Rek\'Sai', title: 'the Void Burrower' },
  '427': { name: 'Ivern', title: 'the Green Father' },
  '429': { name: 'Kalista', title: 'the Spear of Vengeance' },
  '432': { name: 'Bard', title: 'the Wandering Caretaker' },
  '497': { name: 'Rakan', title: 'The Charmer' },
  '498': { name: 'Xayah', title: 'the Rebel' },
  '516': { name: 'Ornn', title: 'The Fire below the Mountain' },
  '555': { name: 'Pyke', title: 'the Bloodharbor Ripper' } }