module.exports = { '1': { id: 'Annie', name: 'Annie', title: 'the Dark Child' },
  '2': { id: 'Olaf', name: 'Olaf', title: 'the Berserker' },
  '3': { id: 'Galio', name: 'Galio', title: 'the Colossus' },
  '4': 
   { id: 'TwistedFate',
     name: 'Twisted Fate',
     title: 'the Card Master' },
  '5': 
   { id: 'XinZhao',
     name: 'Xin Zhao',
     title: 'the Seneschal of Demacia' },
  '6': { id: 'Urgot', name: 'Urgot', title: 'the Dreadnought' },
  '7': { id: 'Leblanc', name: 'LeBlanc', title: 'the Deceiver' },
  '8': { id: 'Vladimir', name: 'Vladimir', title: 'the Crimson Reaper' },
  '9': 
   { id: 'Fiddlesticks',
     name: 'Fiddlesticks',
     title: 'the Harbinger of Doom' },
  '10': { id: 'Kayle', name: 'Kayle', title: 'The Judicator' },
  '11': 
   { id: 'MasterYi',
     name: 'Master Yi',
     title: 'the Wuju Bladesman' },
  '12': { id: 'Alistar', name: 'Alistar', title: 'the Minotaur' },
  '13': { id: 'Ryze', name: 'Ryze', title: 'the Rune Mage' },
  '14': { id: 'Sion', name: 'Sion', title: 'The Undead Juggernaut' },
  '15': { id: 'Sivir', name: 'Sivir', title: 'the Battle Mistress' },
  '16': { id: 'Soraka', name: 'Soraka', title: 'the Starchild' },
  '17': { id: 'Teemo', name: 'Teemo', title: 'the Swift Scout' },
  '18': { id: 'Tristana', name: 'Tristana', title: 'the Yordle Gunner' },
  '19': 
   { id: 'Warwick',
     name: 'Warwick',
     title: 'the Uncaged Wrath of Zaun' },
  '20': 
   { id: 'Nunu',
     name: 'Nunu & Willump',
     title: 'the Boy and His Yeti' },
  '21': 
   { id: 'MissFortune',
     name: 'Miss Fortune',
     title: 'the Bounty Hunter' },
  '22': { id: 'Ashe', name: 'Ashe', title: 'the Frost Archer' },
  '23': 
   { id: 'Tryndamere',
     name: 'Tryndamere',
     title: 'the Barbarian King' },
  '24': { id: 'Jax', name: 'Jax', title: 'Grandmaster at Arms' },
  '25': { id: 'Morgana', name: 'Morgana', title: 'Fallen Angel' },
  '26': { id: 'Zilean', name: 'Zilean', title: 'the Chronokeeper' },
  '27': { id: 'Singed', name: 'Singed', title: 'the Mad Chemist' },
  '28': { id: 'Evelynn', name: 'Evelynn', title: 'Agony\'s Embrace' },
  '29': { id: 'Twitch', name: 'Twitch', title: 'the Plague Rat' },
  '30': { id: 'Karthus', name: 'Karthus', title: 'the Deathsinger' },
  '31': 
   { id: 'Chogath',
     name: 'Cho\'Gath',
     title: 'the Terror of the Void' },
  '32': { id: 'Amumu', name: 'Amumu', title: 'the Sad Mummy' },
  '33': { id: 'Rammus', name: 'Rammus', title: 'the Armordillo' },
  '34': { id: 'Anivia', name: 'Anivia', title: 'the Cryophoenix' },
  '35': { id: 'Shaco', name: 'Shaco', title: 'the Demon Jester' },
  '36': { id: 'DrMundo', name: 'Dr. Mundo', title: 'the Madman of Zaun' },
  '37': { id: 'Sona', name: 'Sona', title: 'Maven of the Strings' },
  '38': { id: 'Kassadin', name: 'Kassadin', title: 'the Void Walker' },
  '39': { id: 'Irelia', name: 'Irelia', title: 'the Blade Dancer' },
  '40': { id: 'Janna', name: 'Janna', title: 'the Storm\'s Fury' },
  '41': 
   { id: 'Gangplank',
     name: 'Gangplank',
     title: 'the Saltwater Scourge' },
  '42': { id: 'Corki', name: 'Corki', title: 'the Daring Bombardier' },
  '43': { id: 'Karma', name: 'Karma', title: 'the Enlightened One' },
  '44': { id: 'Taric', name: 'Taric', title: 'the Shield of Valoran' },
  '45': 
   { id: 'Veigar',
     name: 'Veigar',
     title: 'the Tiny Master of Evil' },
  '48': { id: 'Trundle', name: 'Trundle', title: 'the Troll King' },
  '50': { id: 'Swain', name: 'Swain', title: 'the Noxian Grand General' },
  '51': 
   { id: 'Caitlyn',
     name: 'Caitlyn',
     title: 'the Sheriff of Piltover' },
  '53': 
   { id: 'Blitzcrank',
     name: 'Blitzcrank',
     title: 'the Great Steam Golem' },
  '54': 
   { id: 'Malphite',
     name: 'Malphite',
     title: 'Shard of the Monolith' },
  '55': { id: 'Katarina', name: 'Katarina', title: 'the Sinister Blade' },
  '56': 
   { id: 'Nocturne',
     name: 'Nocturne',
     title: 'the Eternal Nightmare' },
  '57': { id: 'Maokai', name: 'Maokai', title: 'the Twisted Treant' },
  '58': 
   { id: 'Renekton',
     name: 'Renekton',
     title: 'the Butcher of the Sands' },
  '59': 
   { id: 'JarvanIV',
     name: 'Jarvan IV',
     title: 'the Exemplar of Demacia' },
  '60': { id: 'Elise', name: 'Elise', title: 'the Spider Queen' },
  '61': 
   { id: 'Orianna',
     name: 'Orianna',
     title: 'the Lady of Clockwork' },
  '62': { id: 'MonkeyKing', name: 'Wukong', title: 'the Monkey King' },
  '63': { id: 'Brand', name: 'Brand', title: 'the Burning Vengeance' },
  '64': { id: 'LeeSin', name: 'Lee Sin', title: 'the Blind Monk' },
  '67': { id: 'Vayne', name: 'Vayne', title: 'the Night Hunter' },
  '68': { id: 'Rumble', name: 'Rumble', title: 'the Mechanized Menace' },
  '69': 
   { id: 'Cassiopeia',
     name: 'Cassiopeia',
     title: 'the Serpent\'s Embrace' },
  '72': { id: 'Skarner', name: 'Skarner', title: 'the Crystal Vanguard' },
  '74': 
   { id: 'Heimerdinger',
     name: 'Heimerdinger',
     title: 'the Revered Inventor' },
  '75': { id: 'Nasus', name: 'Nasus', title: 'the Curator of the Sands' },
  '76': { id: 'Nidalee', name: 'Nidalee', title: 'the Bestial Huntress' },
  '77': { id: 'Udyr', name: 'Udyr', title: 'the Spirit Walker' },
  '78': { id: 'Poppy', name: 'Poppy', title: 'Keeper of the Hammer' },
  '79': { id: 'Gragas', name: 'Gragas', title: 'the Rabble Rouser' },
  '80': { id: 'Pantheon', name: 'Pantheon', title: 'the Artisan of War' },
  '81': { id: 'Ezreal', name: 'Ezreal', title: 'the Prodigal Explorer' },
  '82': 
   { id: 'Mordekaiser',
     name: 'Mordekaiser',
     title: 'the Iron Revenant' },
  '83': { id: 'Yorick', name: 'Yorick', title: 'Shepherd of Souls' },
  '84': { id: 'Akali', name: 'Akali', title: 'the Rogue Assassin' },
  '85': 
   { id: 'Kennen',
     name: 'Kennen',
     title: 'the Heart of the Tempest' },
  '86': { id: 'Garen', name: 'Garen', title: 'The Might of Demacia' },
  '89': { id: 'Leona', name: 'Leona', title: 'the Radiant Dawn' },
  '90': 
   { id: 'Malzahar',
     name: 'Malzahar',
     title: 'the Prophet of the Void' },
  '91': { id: 'Talon', name: 'Talon', title: 'the Blade\'s Shadow' },
  '92': { id: 'Riven', name: 'Riven', title: 'the Exile' },
  '96': 
   { id: 'KogMaw',
     name: 'Kog\'Maw',
     title: 'the Mouth of the Abyss' },
  '98': { id: 'Shen', name: 'Shen', title: 'the Eye of Twilight' },
  '99': { id: 'Lux', name: 'Lux', title: 'the Lady of Luminosity' },
  '101': { id: 'Xerath', name: 'Xerath', title: 'the Magus Ascendant' },
  '102': { id: 'Shyvana', name: 'Shyvana', title: 'the Half-Dragon' },
  '103': { id: 'Ahri', name: 'Ahri', title: 'the Nine-Tailed Fox' },
  '104': { id: 'Graves', name: 'Graves', title: 'the Outlaw' },
  '105': { id: 'Fizz', name: 'Fizz', title: 'the Tidal Trickster' },
  '106': 
   { id: 'Volibear',
     name: 'Volibear',
     title: 'the Thunder\'s Roar' },
  '107': { id: 'Rengar', name: 'Rengar', title: 'the Pridestalker' },
  '110': { id: 'Varus', name: 'Varus', title: 'the Arrow of Retribution' },
  '111': 
   { id: 'Nautilus',
     name: 'Nautilus',
     title: 'the Titan of the Depths' },
  '112': { id: 'Viktor', name: 'Viktor', title: 'the Machine Herald' },
  '113': { id: 'Sejuani', name: 'Sejuani', title: 'Fury of the North' },
  '114': { id: 'Fiora', name: 'Fiora', title: 'the Grand Duelist' },
  '115': { id: 'Ziggs', name: 'Ziggs', title: 'the Hexplosives Expert' },
  '117': { id: 'Lulu', name: 'Lulu', title: 'the Fae Sorceress' },
  '119': 
   { id: 'Draven',
     name: 'Draven',
     title: 'the Glorious Executioner' },
  '120': { id: 'Hecarim', name: 'Hecarim', title: 'the Shadow of War' },
  '121': { id: 'Khazix', name: 'Kha\'Zix', title: 'the Voidreaver' },
  '122': { id: 'Darius', name: 'Darius', title: 'the Hand of Noxus' },
  '126': { id: 'Jayce', name: 'Jayce', title: 'the Defender of Tomorrow' },
  '127': { id: 'Lissandra', name: 'Lissandra', title: 'the Ice Witch' },
  '131': { id: 'Diana', name: 'Diana', title: 'Scorn of the Moon' },
  '133': { id: 'Quinn', name: 'Quinn', title: 'Demacia\'s Wings' },
  '134': { id: 'Syndra', name: 'Syndra', title: 'the Dark Sovereign' },
  '136': 
   { id: 'AurelionSol',
     name: 'Aurelion Sol',
     title: 'The Star Forger' },
  '141': { id: 'Kayn', name: 'Kayn', title: 'the Shadow Reaper' },
  '142': { id: 'Zoe', name: 'Zoe', title: 'the Aspect of Twilight' },
  '143': { id: 'Zyra', name: 'Zyra', title: 'Rise of the Thorns' },
  '145': { id: 'Kaisa', name: 'Kai\'Sa', title: 'Daughter of the Void' },
  '150': { id: 'Gnar', name: 'Gnar', title: 'the Missing Link' },
  '154': { id: 'Zac', name: 'Zac', title: 'the Secret Weapon' },
  '157': { id: 'Yasuo', name: 'Yasuo', title: 'the Unforgiven' },
  '161': { id: 'Velkoz', name: 'Vel\'Koz', title: 'the Eye of the Void' },
  '163': { id: 'Taliyah', name: 'Taliyah', title: 'the Stoneweaver' },
  '164': { id: 'Camille', name: 'Camille', title: 'the Steel Shadow' },
  '201': 
   { id: 'Braum',
     name: 'Braum',
     title: 'the Heart of the Freljord' },
  '202': { id: 'Jhin', name: 'Jhin', title: 'the Virtuoso' },
  '203': { id: 'Kindred', name: 'Kindred', title: 'The Eternal Hunters' },
  '222': { id: 'Jinx', name: 'Jinx', title: 'the Loose Cannon' },
  '223': { id: 'TahmKench', name: 'Tahm Kench', title: 'the River King' },
  '236': { id: 'Lucian', name: 'Lucian', title: 'the Purifier' },
  '238': { id: 'Zed', name: 'Zed', title: 'the Master of Shadows' },
  '240': { id: 'Kled', name: 'Kled', title: 'the Cantankerous Cavalier' },
  '245': { id: 'Ekko', name: 'Ekko', title: 'the Boy Who Shattered Time' },
  '254': { id: 'Vi', name: 'Vi', title: 'the Piltover Enforcer' },
  '266': { id: 'Aatrox', name: 'Aatrox', title: 'the Darkin Blade' },
  '267': { id: 'Nami', name: 'Nami', title: 'the Tidecaller' },
  '268': { id: 'Azir', name: 'Azir', title: 'the Emperor of the Sands' },
  '412': { id: 'Thresh', name: 'Thresh', title: 'the Chain Warden' },
  '420': { id: 'Illaoi', name: 'Illaoi', title: 'the Kraken Priestess' },
  '421': { id: 'RekSai', name: 'Rek\'Sai', title: 'the Void Burrower' },
  '427': { id: 'Ivern', name: 'Ivern', title: 'the Green Father' },
  '429': 
   { id: 'Kalista',
     name: 'Kalista',
     title: 'the Spear of Vengeance' },
  '432': { id: 'Bard', name: 'Bard', title: 'the Wandering Caretaker' },
  '497': { id: 'Rakan', name: 'Rakan', title: 'The Charmer' },
  '498': { id: 'Xayah', name: 'Xayah', title: 'the Rebel' },
  '516': 
   { id: 'Ornn',
     name: 'Ornn',
     title: 'The Fire below the Mountain' },
  '555': { id: 'Pyke', name: 'Pyke', title: 'the Bloodharbor Ripper' } }