const queueModes = {
  0: { Map: 'Custom games', Description: 'Custom' },
  70: { Map: "Summoner's Rift", Description: 'One for All games' },
  72: { Map: 'Howling Abyss', Description: '1v1 Snowdown Showdown games' },
  73: { Map: 'Howling Abyss', Description: '2v2 Snowdown Showdown games' },
  75: { Map: "Summoner's Rift", Description: '6v6 Hexakill games' },
  76: { Map: "Summoner's Rift", Description: 'Ultra Rapid Fire games' },
  78: { Map: "Summoner's Rift", Description: 'Mirrored One for All' },
  83: { Map: "Summoner's Rift", Description: 'Co-op vs AI Ultra Rapid Fire games' },
  96: { Map: 'Crystal Scar', Description: 'Ascension games' },
  98: { Map: 'Twisted Treeline', Description: '6v6 Hexakill games' },
  100: { Map: "Butcher's Bridge", Description: '5v5 ARAM games' },
  300: { Map: 'Howling Abyss', Description: 'King Poro games' },
  310: { Map: "Summoner's Rift", Description: 'Nemesis games' },
  313: { Map: "Summoner's Rift", Description: 'Black Market Brawlers games' },
  317: { Map: 'Crystal Scar', Description: 'Definitely Not Dominion games' },
  318: { Map: "Summoner's Rift", Description: 'All Random URF games' },
  325: { Map: "Summoner's Rift", Description: 'All Random games' },
  400: { Map: "Summoner's Rift", Description: '5v5 Draft Pick games' },
  420: { Map: "Summoner's Rift", Description: '5v5 Ranked Solo games' },
  430: { Map: "Summoner's Rift", Description: '5v5 Blind Pick Games' },
  450: { Map: 'Howling Abyss', Description: '5v5 ARAM games' },
  460: { Map: 'Twisted Treeline', Description: '3v3 Blind Pick games' },
  470: { Map: 'Twisted Treeline', Description: '3v3 Ranked Flex games' },
  600: { Map: "Summoner's Rift", Description: 'Blood Hunt Assassin games' },
  610: { Map: 'Cosmic Rift', Description: 'Dark Star games' },
  800: { Map: 'Twisted Treeline', Description: 'Co-op vs. AI Intermediate Bot games' },
  810: { Map: 'Twisted Treeline', Description: 'Co-op vs. AI Intro Bot games' },
  820: { Map: 'Twisted Treeline', Description: 'Co-op vs. AI Beginner Bot games' },
  830: { Map: "Summoner's Rift", Description: 'Co-op vs. AI Intro Bot games' },
  840: { Map: "Summoner's Rift", Description: 'Co-op vs.. AI Beginner Bot games' },
  850: { Map: "Summoner's Rift", Description: 'Co-op vs. AI Intermedite Bot games' },
  940: { Map: "Summoner's Rift", Description: 'Nexus Siege games' },
  950: { Map: "Summoner's Rift", Description: 'Doom Bots games /w difficulty voting' },
  960: { Map: "Summoner's Rift", Description: 'Doom Bots games' },
  980: { Map: 'Valoran City Park', Description: 'Star Guardian Invasion: Normal games' },
  990: { Map: 'Valoran City Park', Description: 'Star Guardian Invasion: Onslaught games' },
  1000: { Map: 'Overcharge', Description: 'PROJECT: Hunters games' },
};

export default queueModes;
