const queueModes = {
  0: { map: 'Custom games', description: 'Custom' },
  2: { map: "Summoner's Rift", description: '5v5 Blind Pick games' },
  4: { map: "Summoner's Rift", description: '5v5 Ranked Solo games' },
  6: { map: "Summoner's Rift", description: '5v5 Ranked Premade games' },
  7: { map: "Summoner's Rift", description: 'Co-op vs. AI games' },
  8: { map: 'Twisted Treeline', description: '3v3 Normal games' },
  9: { map: 'Twisted Treeline', description: '3v3 Ranked Flex games' },
  14: { map: "Summoner's Rift", description: '5v5 Draft Pick games' },
  16: { map: 'Crystal Scar', description: '5v5 Dominion Blind Pick games' },
  17: { map: 'Crystal Scar', description: '5v5 Dominion Draft Pick games' },
  25: { map: 'Crystal Scar', description: 'Dominion Co-op vs. AI games' },
  31: { map: "Summoner's Rift", description: 'Co-op vs. AI Intro Bot games' },
  32: { map: "Summoner's Rift", description: 'Co-op vs. AI Beginner Bot games' },
  33: { map: "Summoner's Rift", description: 'Co-op vs. AI Intermediate Bot games' },
  41: { map: 'Twisted Treeline', description: '3v3 Ranked Team games' },
  42: { map: "Summoner's Rift", description: '5v5 Ranked Team games' },
  52: { map: 'Twisted Treeline', description: 'Co-op vs. AI games' },
  61: { map: "Summoner's Rift", description: '5v5 Team Builder games' },
  65: { map: 'Howling Abyss', description: '5v5 ARAM games' },
  70: { map: "Summoner's Rift", description: 'One for All games' },
  72: { map: 'Howling Abyss', description: '1v1 Snowdown Showdown games' },
  73: { map: 'Howling Abyss', description: '2v2 Snowdown Showdown games' },
  75: { map: "Summoner's Rift", description: '6v6 Hexakill games' },
  76: { map: "Summoner's Rift", description: 'Ultra Rapid Fire games' },
  78: { map: "Summoner's Rift", description: 'Mirrored One for All' },
  83: { map: "Summoner's Rift", description: 'Co-op vs AI Ultra Rapid Fire games' },
  91: { map: "Summoner's Rift", description: 'Doom Bots Rank 1 games' },
  92: { map: "Summoner's Rift", description: 'Doom Bots Rank 2 games' },
  93: { map: "Summoner's Rift", description: 'Doom Bots Rank 5 games' },
  96: { map: 'Crystal Scar', description: 'Ascension games' },
  98: { map: 'Twisted Treeline', description: '6v6 Hexakill games' },
  100: { map: "Butcher's Bridge", description: '5v5 ARAM games' },
  300: { map: 'Howling Abyss', description: 'King Poro games' },
  310: { map: "Summoner's Rift", description: 'Nemesis games' },
  313: { map: "Summoner's Rift", description: 'Black Market Brawlers games' },
  315: { map: "Summoner's Rift", description: 'Nexus Siege games' },
  317: { map: 'Crystal Scar', description: 'Definitely Not Dominion games' },
  318: { map: "Summoner's Rift", description: 'All Random URF games' },
  325: { map: "Summoner's Rift", description: 'All Random games' },
  400: { map: "Summoner's Rift", description: '5v5 Draft Pick games' },
  410: { map: "Summoner's Rift", description: '5v5 Ranked Dynamic games' },
  420: { map: "Summoner's Rift", description: '5v5 Ranked Solo games' },
  430: { map: "Summoner's Rift", description: '5v5 Blind Pick Games' },
  440: { map: "Summoner's Rift", description: '5v5 Ranked Flex games' },
  450: { map: 'Howling Abyss', description: '5v5 ARAM games' },
  460: { map: 'Twisted Treeline', description: '3v3 Blind Pick games' },
  470: { map: 'Twisted Treeline', description: '3v3 Ranked Flex games' },
  600: { map: "Summoner's Rift", description: 'Blood Hunt Assassin games' },
  610: { map: 'Cosmic Rift', description: 'Dark Star games' },
  800: { map: 'Twisted Treeline', description: 'Co-op vs. AI Intermediate Bot games' },
  810: { map: 'Twisted Treeline', description: 'Co-op vs. AI Intro Bot games' },
  820: { map: 'Twisted Treeline', description: 'Co-op vs. AI Beginner Bot games' },
  830: { map: "Summoner's Rift", description: 'Co-op vs. AI Intro Bot games' },
  840: { map: "Summoner's Rift", description: 'Co-op vs.. AI Beginner Bot games' },
  850: { map: "Summoner's Rift", description: 'Co-op vs. AI Intermedite Bot games' },
  900: { map: "Summoner's Rift", description: 'ARURF games' },
  910: { map: 'Crystal Scar', description: 'Ascension games' },
  920: { map: 'Howling Abyss', description: 'Legend of the Poro King games' },
  940: { map: "Summoner's Rift", description: 'Nexus Siege games' },
  950: { map: "Summoner's Rift", description: 'Doom Bots games /w difficulty voting' },
  960: { map: "Summoner's Rift", description: 'Doom Bots games' },
  980: { map: 'Valoran City Park', description: 'Star Guardian Invasion: Normal games' },
  990: { map: 'Valoran City Park', description: 'Star Guardian Invasion: Onslaught games' },
  1000: { map: 'Overcharge', description: 'PROJECT: Hunters games' },
};

export default queueModes;
